In [41]:
from sklearn.feature_selection import mutual_info_regression, SelectKBest, mutual_info_classif
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random
import numpy as np

In [42]:
random.seed(57)

In [43]:
df = pd.read_excel('/home/gabriel/Desktop/multivariate-statistics2/d1.xlsx')
df.head()

<ipython-input-43-e1fc943661c9>:1: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  df = pd.read_excel('/home/gabriel/Desktop/multivariate-statistics2/d1.xlsx')


L  G   X0   X1   X2    X3    X4    X5    X6    X7    X8
0  rm  m  141  126  104  81.0  31.8  65.7  50.9  44.0  18.2
1  rm  m  151  128  111  80.4  33.8  69.8  52.7  43.2  18.5
2  rm  m  152  126  108  85.7  34.7  69.1  49.3  45.6  17.9
3  rm  m  141  125  109  83.1  34.0  68.0  48.2  43.8  18.4
4  rm  m  143  126  107  81.9  34.0  66.1  49.0  42.4  17.9

In [70]:
X = df.iloc[:,2:11]
y = df.iloc[:,0]

In [64]:
sel_mi = SelectKBest(score_func = mutual_info_classif, k = 4)
fit_mi = sel_mi.fit(X,y)
fit_mi.scores_

array([0.02864083, 0.39709567, 0.41099003, 0.02087604, 0.0118948 ,
       0.02109682, 0.01553982, 0.09756246, 0.03938253])

In [71]:
X.columns[sel_mi.get_support()]

Index(['X1', 'X2', 'X7', 'X8'], dtype='object')

In [72]:
X = X[X.columns[sel_mi.get_support()]]
X.head()

X1   X2    X7    X8
0  126  104  44.0  18.2
1  128  111  43.2  18.5
2  126  108  45.6  17.9
3  125  109  43.8  18.4
4  126  107  42.4  17.9

In [73]:
X_matrix = X.to_numpy()
X_matrix

array([[126. , 104. ,  44. ,  18.2],
       [128. , 111. ,  43.2,  18.5],
       [126. , 108. ,  45.6,  17.9],
       [125. , 109. ,  43.8,  18.4],
       [126. , 107. ,  42.4,  17.9],
       [128. , 110. ,  40.2,  18.2],
       [116. , 102. ,  39. ,  16.8],
       [120. , 103. ,  41.1,  16.9],
       [116. , 103. ,  44.2,  17. ],
       [117. ,  99. ,  37.1,  17.2],
       [115. , 100. ,  40.5,  17.7],
       [117. , 106. ,  38.2,  18.2],
       [117. , 101. ,  41.5,  19. ],
       [117. , 103. ,  43.7,  17.8],
       [119. , 101. ,  41.1,  18.7],
       [115. , 102. ,  42. ,  18.2],
       [117. , 100. ,  37.6,  17.7],
       [114. , 102. ,  37.8,  17.2],
       [110. ,  94. ,  40.4,  18.1],
       [112. ,  94. ,  42.7,  17.7],
       [109. ,  91. ,  41.2,  17.1],
       [112. ,  99. ,  40.9,  18.3],
       [112. ,  99. ,  34.1,  17.5],
       [113. ,  97. ,  43.6,  17.2],
       [107. ,  97. ,  37.3,  16.5]])

In [74]:
var_cov = np.cov(X_matrix.T)
var_cov

array([[36.74      , 27.12      ,  7.627     ,  1.79983333],
       [27.12      , 25.47666667,  4.25933333,  1.26033333],
       [ 7.627     ,  4.25933333,  7.69043333,  0.55711667],
       [ 1.79983333,  1.26033333,  0.55711667,  0.41173333]])

In [76]:
phi = np.corrcoef(X_matrix.T)
phi

array([[1.        , 0.8864389 , 0.45374177, 0.46275882],
       [0.8864389 , 1.        , 0.30429507, 0.38914021],
       [0.45374177, 0.30429507, 1.        , 0.31308534],
       [0.46275882, 0.38914021, 0.31308534, 1.        ]])

In [77]:
var_eigenvalue, var_eigenvector = np.linalg.eig(var_cov)
var_eigenvector[:, 0] @ var_eigenvector[:, 0]

0.9999999999999998

In [88]:
phi_eigenvalue, phi_eigenvector = np.linalg.eig(phi)
phi_eigenvector[:, 0] @ phi_eigenvector[:, 1]

-5.551115123125783e-16

In [95]:
def normalize_eigenvector(arr, eigenvalues):
    sum_squared = 0
    for i in range(len(eigenvalues)):
        norm = (arr[:,i]**2).sum()
        arr[:,i] = arr[:,i]/norm
    return arr

In [127]:
A = np.zeros((4,4))
A = np.matmul(np.matmul(var_eigenvector,np.diag(var_eigenvalue)),var_eigenvector.T)
A

array([[36.74      , 27.12      ,  7.627     ,  1.79983333],
       [27.12      , 25.47666667,  4.25933333,  1.26033333],
       [ 7.627     ,  4.25933333,  7.69043333,  0.55711667],
       [ 1.79983333,  1.26033333,  0.55711667,  0.41173333]])

In [116]:
normalize_eigenvector(var_eigenvector, var_eigenvalue).

array([[ 0.7676604 ,  0.61895609,  0.16179337,  0.03760014],
       [ 0.12918957, -0.39947025,  0.90688409,  0.03598368],
       [ 0.62579107, -0.67620853, -0.38797914,  0.0244897 ],
       [-0.04891928,  0.00767443, -0.02926343,  0.99834446]])

array([[60.30219138,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  6.92285896,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.77688403,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.31689897]])